### PR TITLE
Added TSRL.RandomPoint for TPointArray's

### PR DESCRIPTION
**Pull request by StickToTheScript**
Generates a random point inside of a TPointArray. Allows for random points on uniquely-shaped objects.

### CODE REVIEW

**Comment by ollydev** [comment]
How about something like this?
- 100 attempts to find a point else return middle. You'd have to have a pretty unlucky shape for this to happen.
- `TPA.MinAreaRect.Bounds` is same as `TPA.Bounds`

```pascal
function TSRL.RandomPoint(TPA: TPointArray): TPoint; overload;
var
  Box: TBox;
begin
  Box := TPA.Bounds;

  for 1 to 100 do // 100 tries
  begin
    Result := TSRL.RandomPoint(Box);
    if SRL.PointInPoly(Result, TPA) then
      Exit(Result);
  end;

  Result := TPA.Mean();
end;
```

**Comment by MerlijnWajer** [comment]
The mean is not guaranteed to be in the poly either, is it?

**Comment by ollydev** [comment]
No it's not. Prehaps we should do this properly and triangulate the polygon and pick a triangle.

**Comment by MerlijnWajer** [comment]
IIUC you could also just pick any of the points that define a corner as fallback?

**Comment by StickToTheScript** [comment]
Perhaps you could pick the middle of a triangle of three random points in the TPA if the PointInPoly fails a certain number of times?

**Pull request closed without merging**
